version: "3.3"
services:
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Organize::333
    ports:
      - 1433:1433
    volumes:
      - db_data:/var/opt/mssql
volumes:
  db_data: